### ISSUE TITLE
Is there a way for a repeated message to be optional too? Should this be default?

### ISSUE THREAD

**Issue by frederikhors** [timostamm/protobuf-ts#109] opened 2021-06-02 22:34 UTC
I have this proto:

```proto
syntax = "proto3";

service PlayerService {
  rpc PlayerList(PlayerListRequest) returns (PlayerListResponse) {}
}

message PlayerListRequest {
  Condition condition = 1;
}

message Condition {
  repeated FilterBy filterBy = 1;
}

message FilterBy {
  string field = 1;
  string value = 2;
}
```

But if I use this in ts like this:

```ts
let condition = {}; // I wanna use it empty here, without filterBy
const players = await playerList({ condition });
```

it throws with this error:

```
query.js:229 TypeError: Cannot read property 'length' of undefined
  at Condition$Type.internalBinaryWrite (common.ts:120)
  at PlayerListRequest$Type.internalBinaryWrite (player.ts:410)
  at PlayerListRequest$Type.toBinary (message-type.js:118)
  at GrpcWebFetchTransport.unary (grpc-web-transport.js:111)
  at tail (rpc-interceptor.js:10)
  at stackIntercept (rpc-interceptor.js:15)
```

**Why?**

These are the `common.ts` lines:

```ts
/**
 * @generated from protobuf message api.v1.Condition
 */
export interface Condition {
  /**
    * @generated from protobuf field: repeated api.v1.FilterBy filterBy = 1;
    */
  filterBy: FilterBy[];
}

// ...

internalBinaryWrite(message: Condition, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
  /* repeated api.v1.FilterBy filterBy = 1; */
  for (let i = 0; i < message.filterBy.length; i++)
      FilterBy.internalBinaryWrite(message.filterBy[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
  /* string search = 2; */
  if (message.search !== "")
      writer.tag(2, WireType.LengthDelimited).string(message.search);
  let u = options.writeUnknownFields;
  if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
  return writer;
}
```

I'm using:

```json
"@protobuf-ts/grpcweb-transport": "2.0.0-alpha.20",
"@protobuf-ts/plugin": "2.0.0-alpha.20",
```

**Comment by timostamm** [comment] 2021-06-02 23:26
If you want to create a `Condition`, you have to set `filterBy` as well. It can be an empty array, but the property has to be present:

```ts
let condition: Condition = { filterBy: [] };
```

It would be really convenient if the rpc client accepted a partial message. This is tracked in #62. This is not completely trivial to change, unfortunately.

As an alternative, you can use `create()`:

```ts
let condition = Condition.create();
```

Duplicate of #62

**Closed by timostamm** 2021-06-02 23:26 UTC

**Comment by frederikhors** [comment] 2021-06-03 10:32
Thanks for the answer.

Just to understand if I understand: even if I use

```ts
let condition = Condition.create();
```

every time I need to change it with

```ts
condition = { somethingElse: "hello" }
```

it throws with:

```
Property 'filterBy' is missing in type '{ somethingElse: string; }' but required in type 'Condition'.ts (2741)
```

so I need to use it like this:

```ts
condition = { ...condition, somethingElse: "hello" }
```

Right?

**Do you see more effective alternative ways?**

**Comment by timostamm** [comment] 2021-06-03 12:25
Thats just the nature. `condition = ...` replaces the value, but if the type does not match (because you left out a property), the compiler complains.

You could simple do:

```ts
condition.somethingElse = "hello"
```

Or (if you _want_ the value of condition to be replaced)

```ts
condition = {...condition, somethingElse: "hello"}
```

**Comment by frederikhors** [comment] 2021-06-03 12:55
The second one because I'm using Svelte and it needs reassign. Thanks again!
