### ISSUE TITLE
Duration well known type not supported

### ISSUE THREAD

**Issue by delaneyj** [timostamm/protobuf-ts#365] opened 2022-08-19 03:43 UTC
In feature it says 
> supports all [well-known-types](https://github.com/timostamm/protobuf-ts/blob/master/MANUAL.md#well-known-types) with custom JSON representation and helper methods

but [google.protobuf.Duration](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/duration.proto) is not supported.  It has the same structure as a Timestamp but different contextual meaning.

**Comment by timostamm** [comment] 2022-08-19 06:07
Take a look at how `Duration` serializes to JSON - it's very different from `Timestamp'. Closing this because "not supported" does not seem accurate - unless a regression somehow slipped by the [tests](https://github.com/timostamm/protobuf-ts/blob/master/packages/test-generated/spec/google.protobuf.duration.spec.ts). Please LMK if you are aware of something in that regard.

If you have some ideas for helper functions specific to `Duration`, I'm all ears (we don't really have any standard except `Date`, so I've found that a bit difficult without pulling in the kitchen sink). Note that the [plan](https://github.com/timostamm/protobuf-ts/issues/356) is to switch to the base types of protobuf-es, so the preferable way forward would be to add helpers there.

**Closed by timostamm** 2022-08-19 06:07 UTC
Labels: post-protobuf-es
