### ISSUE TITLE
Support promises in interceptors?

### ISSUE THREAD

**Issue by someone1** [timostamm/protobuf-ts#31] opened 2020-11-23 22:54 UTC
Is there a way to accept promises in interceptors? The use case I have is I plan on using [auth0-spa-js](https://github.com/auth0/auth0-spa-js) which will [handle retrieving/refreshing Access Tokens](https://auth0.github.io/auth0-spa-js/classes/auth0client.html#gettokensilently) as necessary, but does so with a Promise callback. I'd like my interceptor to use this directly, but for now I've gotten around it by "caching" the token myself and setting a timer to run every minute to update the cached value directly from the auth0 client.

**Comment by timostamm** [comment] 2020-11-24 14:54
Hey @someone1 

this should work. Let me know if you get any problems.


```typescript
function fetchToken(): Promise<string> {
  console.log('fetchToken() fetching a token asynchronously...');
  return new Promise<string>(resolve => {
    setTimeout(() => {
      console.log('fetchToken() got the token');
      resolve('example-token');
    }, 1250);
  });
}


const fetchTokenInterceptor: RpcInterceptor = {
  interceptUnary(next, method, input, options): UnaryCall {
    console.log(`fetchTokenInterceptor intercepting unary call: ${method.service.typeName} / ${method.name}`);

    // next() creates a call instance, sending data (including headers) to the server.
    // we want to wait until we have our token:
    const callPromise = new Promise<UnaryCall<any, any>>(resolve => {
      fetchToken().then(token => {
        if (!options.meta) {
          options.meta = {};
        }
        console.log(`fetchTokenInterceptor setting authorization = ${token}`);
        options.meta.Authorization = token;
        resolve(next(method, input, options));
      });
    });

    // we have to return a valid call instance immediately.
    // we wrap the promised call.
    return new UnaryCall<any, any>(
      method,
      options.meta ?? {},
      input,
      callPromise.then(c => c.headers),
      callPromise.then(c => c.response),
      callPromise.then(c => c.status),
      callPromise.then(c => c.trailers),
    );
  }
};

```

**Comment by someone1** [comment] 2020-11-24 15:47
Ahhh - thank you! I got as far as trying to return `callPromise` in your example, didn't check to make a new `UnaryCall`  which does support promises.

It doesn't seem I can do the same trick for server streaming calls though - any suggestions there?

**Comment by timostamm** [comment] 2020-11-24 17:15
There are a couple of more gotchas with streaming calls, but this should work. 

Basically also create an own output stream to have one ready ahead of time and delegate.


```typescript
const fetchTokenInterceptor: RpcInterceptor = {

  interceptServerStreaming(next, method, input, options): ServerStreamingCall {
    console.log(`fetchTokenInterceptor intercepting server streaming call: ${method.service.typeName} / ${method.name}`);

    // we have to return an output stream instance before we get one
    // from next(), so we create our own and delegate data below...
    const outputStream = new RpcOutputStreamController();

    // next() creates a call instance, sending data (including headers) to the server.
    // we want to wait until we have our token:
    const callPromise = new Promise<[ServerStreamingCall]>((resolve, reject) => {
      fetchToken().then(token => {
        if (!options.meta) {
          options.meta = {};
        }
        console.log(`fetchTokenInterceptor setting authorization = ${token}`);
        options.meta.Authorization = token;

        // start the call
        const call = next(method, input, options);

        // delegate from the original output stream to the one controlled by us
        call.response.onNext((message, error, done) => {
          if (message)
            outputStream.notifyMessage(message);
          if (error)
            outputStream.notifyError(error);
          if (done)
            outputStream.notifyComplete();
        });

        // deliberately returning a tuple. the call is awaitable - the promise chain
        // would wait until the call is finished.
        resolve([call]);
      }, reason => {
        console.error('fetchTokenInterceptor failed to fetch token', reason);
        const err = new RpcError(`Failed to fetch token`, 'INTERNAL');
        outputStream.notifyError(err);
        reject(err);
      });
    });

    // we have to return a valid call instance immediately.
    // we wrap the promised call.
    return new ServerStreamingCall(
      method,
      options.meta ?? {},
      input,
      callPromise.then(c => c[0].headers),
      outputStream,
      callPromise.then(c => c[0].status),
      callPromise.then(c => c[0].trailers),
    );
  }

};
```

**Comment by someone1** [comment] 2020-11-24 19:46
thanks again! Both methods seem to work though they require some specific wiring - would there be room to enhance interceptors to support promises in a future update? 

Not a huge deal as it clearly works today as-is - just thinking about future changes that would require additional maintenance to these workarounds should the API surface change in a way that would otherwise not affect a simpler implementation.

**Comment by timostamm** [comment] 2020-11-24 20:14
You're welcome. 

I have to admit that the required code is not intuitive at all. I never considered the use case when designing the API, unfortunately. 

The Call classes have a reasonable API. But maybe the internals need something a little bit more basic. That should also improve the code for method styles (PR #10, not released yet).

**Comment by someone1** [comment] 2020-11-25 18:56
Just for completeness, the last `done` check should be:

```
if (done && !outputStream.closed)
            outputStream.notifyComplete();
```

for some reason it was notifying complete multiple times

**Comment by timostamm** [comment] 2020-11-27 11:52
> Just for completeness, the last `done` check should be:
> 
> ```
> if (done && !outputStream.closed)
>             outputStream.notifyComplete();
> ```
> 
> for some reason it was notifying complete multiple times

That was actually a bug caused by ambiguous meaning of the "done" arg. Fixed in master, but is technically a breaking change, so this is only going to hit in 2.0, see CHANGELOG. 

Your workaround will still work with the fix.

**Closed by timostamm** 2020-11-27 11:52 UTC

**Comment by Mustang-Galaxy** [comment] 2021-12-14 03:09
> You're welcome.
> 
> I have to admit that the required code is not intuitive at all. I never considered the use case when designing the API, unfortunately.
> 
> The Call classes have a reasonable API. But maybe the internals need something a little bit more basic. That should also improve the code for method styles (PR #10, not released yet).

Why isn't my interceptServerStreaming called when have a response？

**Comment by timostamm** [comment] 2021-12-14 08:11
> Why isn't my interceptServerStreaming called when have a response？

Have a look at the example here: https://github.com/timostamm/protobuf-ts/blob/master/packages/runtime-rpc/src/rpc-interceptor.ts
