### ISSUE TITLE
invalid url for latest v27.0-rc1 release

### ISSUE THREAD

**Issue by austinmcdaniel** [timostamm/protobuf-ts#646] opened 2024-04-18 19:35 UTC
Error:
@protobuf-ts/protoc failed to download protoc v27.0-rc1. 
  Did you misspell the version number? The version number must look like "3.0.12", without a leading "v".
##[error]EXEC(0,0): Error : HTTP 404 for https://github.com/protocolbuffers/protobuf/releases/download/v27.0-rc1/protoc-27.0-rc1-linux-x86_64.zip

the URL should be 
https://github.com/protocolbuffers/protobuf/releases/download/v27.0-rc1/protoc-27.0-rc-1-linux-x86_64.zip

Arguably this is the protobuf team's fault since they used a different naming convention, but it will break anyone using this project without specifying a protoc installation or version.

**Comment by timostamm** [comment] 2024-04-18 21:36
Closing as a duplicate of https://github.com/timostamm/protobuf-ts/issues/645

**Closed by timostamm** 2024-04-18 21:36 UTC
