### ISSUE TITLE
If the server starts after the call, the client does not "recognize" the server has started and the waiting for a response is infinite.

### ISSUE THREAD

**Issue by frederikhors** [timostamm/protobuf-ts#125] opened 2021-07-02 17:42 UTC
I'm using `grpc-web-transport`.

```ts
export const transport = new GrpcWebFetchTransport({ baseUrl: '/', format: 'binary' });

export const userService = new UserServiceClient(transport);
```

Sometimes the server isn't started yet and starts after the browser request. But - unlike the classic REST call, in ajax or similar - even if the server starts, my client can't contact the server that started late.

Why?

**Comment by optiman** [comment] 2021-07-03 18:20
Hard to say why it can't connect, but `fetch()` has no default request timeout and is cancelled only by the browser itself after a while.

You can create an `AbortController` and set [`RpcOptions.abort`](https://github.com/timostamm/protobuf-ts/blob/f66934c6ef796090c2ce320252fdc4c0b58de732/packages/runtime-rpc/src/rpc-options.ts#L55) for every request (or better create an interceptor that will create abort controllers with a default timeout).

Some examples of `AbortController` usage:
https://dmitripavlutin.com/timeout-fetch-request/

**Comment by timostamm** [comment] 2021-07-05 09:11
What's the status of the request in the browser? Did it fail because the server wasn't responding yet? 

The request will not be retried automatically. You'll have to add some logic to handle that error and retry, or tell the user to refresh the page.

**Comment by frederikhors** [comment] 2021-07-06 11:06
> What's the status of the request in the browser?

Pending...

> Did it fail because the server wasn't responding yet?

It does not fail. It's in pending state forever...

I start my client web app. The server is not started yet... I start the server... The client does not "recognize" the server is started and the call is in pending state forever...

With REST or GraphQL API in other projects as soon the server starts it works!

**Comment by timostamm** [comment] 2021-07-07 19:36
This could have many reasons and needs a close look at client and server implementations. I can't reproduce with the [chat example](https://github.com/timostamm/protobuf-ts/tree/master/packages/example-chat-system/browser-client), though. The request fails with a net::ERR_CONNECTION_REFUSED as expected.

Closing this, but please reopen in case you find a deficit.

**Closed by timostamm** 2021-07-07 19:36 UTC
